name: Build Image 2 HW_SWR (GX_I/M)

on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3    

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4        
        with:
          context: ./modules
          dockerfile: Dockerfile
          push: true                    
          registry: swr.cn-south-1.myhuaweicloud.com
          repository: ym/nginx
          build-args: |
            ENABLED_MODULES=headers-more
          tags: |
            1.0
            latest


    
