name: Build Image 2 HW_SWR (GX_I/M)

on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3    

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          directory: ./modules
          image: ym/nginx
          tags: 1.0, latest
          registry: swr.cn-south-1.myhuaweicloud.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          maxRetryAttempts: 3
          retryDelaySeconds: 5                 
          buildArgs: |
            ENABLED_MODULES="headers-more"
