name: Build Image 2 HW_SWR (GX_I/M)

on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEI_SWR_USERNAME }}
          password: ${{ secrets.HUAWEI_SWR_PWD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./modules
          push: true                    
          build-args: |
            ENABLED_MODULES=headers-more
          tags: |
            ym/nginx:1.0
            ym/nginx:latest


    
